In [15]:
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

x=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

clf=SVC(C=1e5,kernel='linear')
clf.fit(x,y)

print('w= ',clf.coef_)
print('b= ',clf.intercept_)
print('Indices of support vectors = ',clf.support_)
print('Support vectors = ',clf.support_vectors_)
print('Number of support vectors for each class = ',clf.n_support_)
print('Coefficients of the support vector in the decision function = ',np.abs(clf.dual_coef_))



df=pd.read_csv("/content/sample_data/glass.csv")
print("dataset",df)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(df))

x=df.drop('Type',axis=1)
y=df.Type





w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors =  [2 3]
Support vectors =  [[ 2.  3.]
 [ 6. -1.]]
Number of support vectors for each class =  [1 1]
Coefficients of the support vector in the decision function =  [[0.0625 0.0625]]
dataset       Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe  Type
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  213  1.51651  14

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


from sklearn import svm
ml=svm.SVC(kernel='linear')
ml.fit(x_train,y_train)


print(ml.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.48000e+02 1.51610e+00 1.33300e+01 3.53000e+00 1.34000e+00 7.26700e+01
  5.60000e-01 8.33000e+00 0.00000e+00 0.00000e+00]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]


In [17]:
print(ml.n_support_)

[1 2 2 4 3 2]


In [18]:
y_pred=ml.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy Score",accuracy_score(y_test,y_pred))

print("Confusion Matrix",confusion_matrix(y_test,y_pred))

print("Classification Report",classification_report(y_test,y_pred))

Accuracy Score 1.0
Confusion Matrix [[26  0  0  0  0  0]
 [ 0 23  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]
Classification Report               precision    recall  f1-score   support

           1       1.00      1.00      1.00        26
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00         3
           5       1.00      1.00      1.00         4
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         7

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [19]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

#With Different Kernels

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [20]:
ypred1=model1.predict(x_test)
ypred2=model2.predict(x_test)
ypred3=model3.predict(x_test)

print("Accuracy Score of kernel 1",accuracy_score(y_test,ypred1))

print("Accuracy Score of kernel 2",accuracy_score(y_test,ypred2))

print("Accuracy Score of kernel 3",accuracy_score(y_test,ypred3))







Accuracy Score of kernel 1 0.6923076923076923
Accuracy Score of kernel 2 0.9846153846153847
Accuracy Score of kernel 3 0.8615384615384616


In [21]:
#Array method of using different kernels

[{'kernel':['rbf'],'gamma':[1e-3,1e-4],
     'C':[1,10,100,1000]},
{'kernel':['linear'],'C':[1,10,100,1000]},
{'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]},
{'kernel':['sigmoid'],'C':[1,10,100,1000],'gamma':[1e-3,1e-4,1e-5]}]

[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
 {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
 {'degree': [2, 3, 4], 'gamma': [0.001, 0.0001], 'kernel': ['poly']},
 {'C': [1, 10, 100, 1000],
  'gamma': [0.001, 0.0001, 1e-05],
  'kernel': ['sigmoid']}]

In [22]:
params_grid1=[{'kernel':['rbf']},
             {'kernel':['linear']},
             {'kernel':['poly']},
             {'kernel':['sigmoid']}]

In [23]:
from sklearn.model_selection import GridSearchCV
svm_model=GridSearchCV(SVC(),params_grid1,cv=5)
svm_model.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'kernel': ['rbf']}, {'kernel': ['linear']},
                         {'kernel': ['poly']}, {'kernel': ['sigmoid']}])

In [24]:
print('Best score for training data:',svm_model.best_score_,"\n")

#View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n")
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model=svm_model.best_estimator_
Y_pred=final_model.predict(x_test)

Best score for training data: 0.9800000000000001 

Best C: 1.0 

Best Kernel: linear 

Best Gamma: scale 



In [25]:
print(accuracy_score(y_test,Y_pred))

1.0
